### ISSUE TITLE
Npm export error

### ISSUE THREAD

**Issue by yeemachine** [guansss/pixi-live2d-display#14]
```
SyntaxError: The requested module '../web_modules/pixi-live2d-display.js' does not provide an export named 'Live2DModel'
```

I'm getting around it right now by just importing the whole thing, but thought I'd bring it up. 
```
import Live2D_Display from 'pixi-live2d-display';
const Live2DModel = Live2D_Display.Live2DModel
```

**Comment by guansss** [comment]
The path `../web_modules/pixi-live2d-display.js` is strange, as it would typically be `node_modules/pixi-live2d-display/lib/index.js`. I'm wondering how you used this module, could you provide more information?

**Comment by yeemachine** [comment]
I'm currently using Rollup/Snowpack to bundle atm. Here's how im importing.

```
import Live2D_Display from 'pixi-live2d-display';
const {Live2DModel} = Live2D_Display
```

which actually still gets me this error

```
pixi-live2d-display.js:28405 Uncaught (in promise) TypeError: (intermediate value).add(...).load(...).on is not a function
pixi-live2d-display.js:28405 Uncaught (in promise) TypeError: r.on is not a function
```

**Comment by guansss** [comment]
Alright, I realized that "strange" path was generated by Snowpack.

The first problem seems to be an incompatibility between Snowpack and commonjs modules, there's a related [issue](https://github.com/snowpackjs/snowpack/issues/440) with possible solutions. I will consider releasing both the commonjs module and ES module in the future.

And for the second, it's because Pixi has suddenly obsoleted the `EventEmitter` mixin of `PIXI.Loader` in v5.3.0, which made the `on()` method no longer available. The solution is either use a Pixi version lower than 5.3.0, or wait for the next release of this project, which has removed the dependency of `PIXI.Loader`.

**Comment by yeemachine** [comment]
Thanks! yup. Updating PIXI to 5.2.4 worked.
