### ISSUE TITLE
Facerig Demo + Live2D 4.0 in the future?

### ISSUE THREAD

**Issue by yeemachine** [guansss/pixi-live2d-display#6]
Hi again. Just wanted to thank you for the support of this library.
Wanted to share this [demo](https://live2d-facerig.glitch.me/) I've been working on that uses webcam face capture to control Live2D. 

On the topic of a potential future release with Live2D 4.0 compatibility, have you had a chance to peer into their new SDK? Was wondering how easy of an update it would be. 

I know Live2D 4.0 + PIXI V5 is definitely an in demand combo, especially with the vtube community on the rise. Linking another [reference](https://www.html5gamedevs.com/topic/46109-i-want-to-make-the-background-of-the-rendertexture-transparent/) to work being done to make it real. 

Wish I was more technically capable to contribute, but I'll fumble around a bit.

**Comment by guansss** [comment]
Hi! I've tried the demo on my mobile but it didn't seem to capture my face motions, possibly I was missing something?

It's been a while since I put off the development and switched to some more important things, will be back once I finish them.

The progress of 4.0 support had been made to about 40%. The development stage then was refactoring the Live2D 4.0 SDK, it's a grunt work, I'm not sure if things will get hard when I make it to next stage, hopefully they won't. :)

Ultimately, if all goes well, the 4.0 support will be finished before the end of this year.

**Comment by yeemachine** [comment]
Cool! look forward to the update! Glad to hear it's not too drastic of a shift. 

Ah, you might be on an android phone. That's one thing I haven't tested yet. I've only tested it on iPhone and Chrome, Firefox, Safari.

Did [Facerig Model] end up loading on your screen? If that did, then it might just be a matter of how I'm capturing the video feed using canvas. Either way, here's a link to [video tweet](https://twitter.com/yeemachine/status/1309211305581051904?s=20) of the demo. Thanks for trying it out!

**Comment by guansss** [comment]
Yes I'm using Chrome on Android. The Facerig Model ends up loading and is stated as "Ready", but I noticed that the Tracking is always "No", and there are no dots appearing on my captured face. Nothing much I can help :P

I've watched the video, impressive result!
